name: ${project.name}
main: de.Keyle.MyPet.MyPetPlugin
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
author: Keyle
website: ${project.url}
softdepend: [Vault, Heroes, AncientRPG, BattleArena, Minigames, MobArena, pvparena, Multiverse-Core]
commands:
  myPet:
    description: Help for all MyPet commands.
  petname:
    description: Changes the name of your MyPet
    usage: '/<command> <PetName>'
    permission: MyPet.user.command.name
  petcall:
    aliases: [petc, pc]
    description: Calls your MyPet.
  petsendaway:
    aliases: [petsa, psa]
    description: Send your MyPet away.
  petrelease:
    description: Releases your MyPet.
    usage: '/<command> <PetName>'
    permission: MyPet.user.command.release
  petstop:
    aliases: [pets, ps]
    description: Stops your MyPet from attacking.
  petpickup:
    aliases: [petp, pp]
    description: Toogles pickup of your MyPet.
  petinventory:
    aliases: [peti, pi]
    description: Opens the inventory of your MyPet.
  petbehavior:
    aliases: [petb, pb]
    description: Changes the behavior mode of your MyPet.
    usage: '/<command> [<friendly/friend/aggressive/aggro/normal/farm/raid/duel>]'
  petinfo:
    aliases: [pinfo]
    description: Shows info about your MyPet
    usage: '/<command> [PlayerName]'
  petskill:
    aliases: [pskill]
    description: Shows the Skill-levels of your MyPet
    usage: '/<command> <Playername>'
  mypetadmin:
    aliases: [petadmin]
    description: MyPet-Admin-Command -> http://mypet.keyle.de/doku.php?id=en:commands
    permission: MyPet.admin
  petskilltree:
    aliases: [pst, petst]
    description: Shows a fully configured skilltree
    usage: '/<command> <mobtype> [SkillTreeName]'
  petchooseskilltree:
    aliases: [pcst, petcst]
    description: Chooses a skilltree.
    usage: '/<command> <SkillTreeName>'
  petbeacon:
    aliases: [pbeacon]
    description: Beacon!
  petrespawn:
    aliases: [pr, petr]
    description: Pays respawn fee or enable auto respawn fee paying.
    usage: '/<command> [pay/auto] [min respawn time]'
    permission: MyPet.user.command.respawn
  pettype:
    description: Shows info about the MyPet-types.
    usage: '/<command> <Pettype>'
  petcapturehelper:
    aliases: [pch]
    description: Toogles CaptureHelper on/off
    usage: '/<command>'
    permission: MyPet.user.command.capturehelper

permissions:
  MyPet.user.leash.*:
    description: Player can leash all MyPet-Types.
    children:
      MyPet.user.leash.Bat: true
      MyPet.user.leash.Blaze: true
      MyPet.user.leash.CaveSpider: true
      MyPet.user.leash.Chicken: true
      MyPet.user.leash.Cow: true
      MyPet.user.leash.Creeper: true
      MyPet.user.leash.Enderman: true
      MyPet.user.leash.Giant: true
      MyPet.user.leash.Horse: true
      MyPet.user.leash.IronGolem: true
      MyPet.user.leash.MagmaCube: true
      MyPet.user.leash.Mooshroom: true
      MyPet.user.leash.Ocelot: true
      MyPet.user.leash.Pig: true
      MyPet.user.leash.PigZombie: true
      MyPet.user.leash.Sheep: true
      MyPet.user.leash.Silverfish: true
      MyPet.user.leash.Skeleton: true
      MyPet.user.leash.Slime: true
      MyPet.user.leash.Snowman: true
      MyPet.user.leash.Spider: true
      MyPet.user.leash.Squid: true
      MyPet.user.leash.Villager: true
      MyPet.user.leash.Witch: true
      MyPet.user.leash.Wither: true
      MyPet.user.leash.Wolf: true
      MyPet.user.leash.Zombie: true
  MyPet.*:
    description: Gives access to ALL (not includes admin) MyPet features.
    children:
      MyPet.user.*: true
  MyPet.admin:
    description: Gives access to the MyPet admin features.
    default: op
  MyPet.user.*:
    description: Gives access to MyPet features for normal user.
    children:
      MyPet.user.leash.*: true
      MyPet.user.command.respawn: true
      MyPet.user.command.release: true
      MyPet.user.command.capturehelper: true
      MyPet.user.command.name: true
      MyPet.user.command.name.color: true
  MyPet.user.command.release:
    default: true
    description: Allows usage of /petrelease
  MyPet.user.command.capturehelper:
    default: true
    description: Gives access to the CaptureHelper
  MyPet.user.command.respawn:
    default: true
    description: Allows usage of /petrespawn
  MyPet.user.command.name:
    default: true
    description: Allows usage of /petname
  MyPet.user.command.name.color:
    default: true
    description: Allows to use colors in petnames